Documentation:
  CommentFormat: Doxygen

CompileFlags:
  Add:
    - -xc
    - -std=c17
    - -I/opt/homebrew/include
    - -I/opt/homebrew/opt/ncurses/include
    - -pedantic
    - -Wall
    - -Wextra
    - -Wcast-align
    - -Wconversion
    - -Wsign-conversion
    - -Wfloat-equal
    - -Wswitch-default
    - -Wswitch-enum
    - -Wcomma
    - -Wextra-semi-stmt
    - -Wmissing-prototypes
    - -Wmissing-variable-declarations
    - -Wdeclaration-after-statement
    - -Wtautological-unsigned-zero-compare
    - -Wunused-macros
    - -Wvla

---

If:
  PathMatch: .*\.h

CompileFlags:
  Add: -xc-header
